spring.application.name=10-IDENTITY-PK-Generation-PostgreSql

#DataSource Properties

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/sb01db
spring.datasource.username=postgres
spring.datasource.password=root@123

#JPA/Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update