#Admin Service Configuration

admin.url=http://admin.tca.com
admin.port=7071
admin.user=admin
admin.password=root@123

#--> A properties file is an external file (separate from your Java source code) used to store application configuration data as simple key-value pairs.
#--> Its file extension must be .properties
