spring.application.name=03-Banner-App
#this name is used in the log for the entry or which service is not working

spring.main.banner-mode=console
#spring.main.banner-mode=log
#spring.main.banner-mode=log